### ISSUE TITLE
first redirect should allow changing path

### ISSUE THREAD

**Issue by devsnek** [chromium/hstspreload#103]
cloudflare's server redirects from `http://gus.host` to `https://gus.host/` which appears to break the check:

```json
{
  "errors": [
    {
      "code": "redirects.http.no_redirect",
      "summary": "No redirect from HTTP",
      "message": "`http://gus.host` does not redirect to `https://gus.host`."
    }
  ],
  "warnings": []
}
```

later on in the codebase it says "The first redirect should be to a secure page on the same host" which seems to meet this requirement

**Comment by lgarron** [comment]
https://hstspreload.org/api/v2/preloadable?domain=gus.host shows no errors. Can you still reproduce this?

I don't see why redirect wouldn't be detected:
https://github.com/chromium/hstspreload/blob/master/redirects.go#L93

**Comment by devsnek** [comment]
hmm i cannot reproduce this anymore, i guess i'll close this

**Comment by lgarron** [comment]
Alright. Thanks for reporting!
