### ISSUE TITLE
Treat IP addresses differently from normal domains

### ISSUE THREAD

**Issue by ExE-Boss** [chromium/hstspreload#105]
Testing [1.1.1.1](https://hstspreload.org/?domain=1.1.1.1) returns that it’s a subdomain, even though it’s actually an IP address and therefore it should be preloadable.

Same happens with [1.0.0.1](https://hstspreload.org/?domain=1.0.0.1).

The IPv6 adresses of [2606:4700:4700::1111](https://hstspreload.org/api/v2/preloadable?domain=2606:4700:4700::1111) and [2606:4700:4700::1001](https://hstspreload.org/api/v2/preloadable?domain=2606:4700:4700::1001) don’t work through the web interface at all and are identified as TLDs instead.

## See also:
- [Announcing 1.1.1.1: the fastest, privacy-first consumer DNS service - Cloudflare Blog](https://blog.cloudflare.com/announcing-1111/)
- [Introducing DNS Resolver, 1.1.1.1 (not a joke) - Cloudflare Blog](https://blog.cloudflare.com/dns-resolver-1-1-1-1/)
- chromium/hstspreload.org#148

**Comment by martijnc** [comment]
IP addresses are excluded from (dynamic) [HSTS](https://tools.ietf.org/html/rfc6797#appendix-A) (and [HPKP](https://tools.ietf.org/html/draft-ietf-websec-key-pinning-21#section-2.3.3)) and probably shouldn't be preloadable either. Maybe we should detect when an IP address is submitted and improve the error message in that case?

[Chrome](https://cs.chromium.org/chromium/src/net/url_request/url_request_http_job.cc?sq=package:chromium&l=771) and [Firefox](https://hg.mozilla.org/mozilla-central/file/c44f60c43432/security/manager/ssl/nsSiteSecurityService.cpp#l895) also ignore (dynamic) HSTS headers when the hostname is an IP address.

**Comment by lgarron** [comment]
I agree with @martijnc: we shouldn't allow automatic submissions of IPs, but we should detect them and give an appropriate message.
(In particular, the fact that dynamic HSTS isn't supported for IP addresses means that the site can't satisfy the dynamic HSTS requirements.)

However, you could see if adding it to the list directly is feasible, by [contacting the current maintainers](https://hstspreload.org/#contact).

**Comment by ExE-Boss** [comment]
Well, 1.1.1.1 and 1.0.0.1 were added in commit [`5a9976b`](https://chromium.googlesource.com/chromium/src/net/+/5a9976ba51d1243642368137100188c3509f99de%5E%21/) to the chromium repository, but 1.1.1.1 was removed in commit [`36b8980`](https://chromium.googlesource.com/chromium/src/+/36b8980c6b8763633161ee0472e10b4b4fd72ce3%5E%21/) due to [issues with broken middle‑boxes](https://bugs.chromium.org/p/chromium/issues/detail?id=853934).
