### ISSUE TITLE
TestHTTPUnavailable fails 

### ISSUE THREAD

**Issue by phumpal** [chromium/hstspreload#115]
TestHTTPUnavailable fails as the cert for https://oskuro.net/ has expired

https://www.sslshopper.com/ssl-checker.html#hostname=oskuro.net

**Comment by phumpal** [comment]
I believe this is @jmallach. Gentle ping ^^

**Comment by nharper** [comment]
Some tests depend on the behavior of external domains and need to be rewritten to be hermetic.

Duplicate of #112

**Comment by phumpal** [comment]
Awesome thanks @jmallach
