### ISSUE TITLE
Add a consent checkbox to the submission form

### ISSUE THREAD

**Issue by lgarron** [chromium/hstspreload#3]
From https://crbug.com/593204

> e.g.
> 
> [ ] I understand that preloading a domain through this form will require every subdomain of this site to serve a valid certificate (for that subdomain) in order to remain accessible in Chrome.
> 
> I would also like something to the effect of "I am either the owner of this site or have direct authorization form the owner of this site." but this is a silly barrier if the only real verification is the header.

**Comment by craigfrancis** [comment]
Sorry, managed to get pull request https://github.com/chromium/hstspreload/pull/8 to include some basic changes for this as well.

**Comment by craigfrancis** [comment]
Pull request https://github.com/chromium/hstspreload/pull/12
