### ISSUE TITLE
favicon missing

### ISSUE THREAD

**Issue by cem-** [chromium/hstspreload#44]
per [lgarron](https://twitter.com/lgarron/status/717486903872761856) a favicon was requested. Double turnstiles are used to denote tautologies (something which is true), HSTS is used to denote that https must always be used. I combined the turnstile and a padlock for this logo.

(zip has svg source and converted ico)
[hstsPreloadIcon.zip](https://github.com/chromium/hstspreload/files/205756/hstsPreloadIcon.zip)

**Comment by lgarron** [comment]
> Double turnstiles are used to denote tautologies (something which is true), HSTS is used to denote that https must always be used.

Hmm, that's kind of witty, but I don't think that will be clear to everyone viewing this icon. Are there other analogies for "mandatory" or "always" that are more directly evident?

**Comment by cem-** [comment]
true, though i don't think the meaning necessarily needs to be directly evident. It kinda forms an H like the H in https, that may be good enough...

nonetheless, i made a material design version using circles, a notable 'always' symbol. (I didn't want to use the infinity sign since hsts expires.) the arrow is a reference to the 'pre' part of preload.

![hstspreload](https://cloud.githubusercontent.com/assets/1312562/14319200/f0353316-fbd5-11e5-9c67-075e44cbae68.png)

**Comment by lgarron** [comment]
> nonetheless, i made a material design version using circles, a notable 'always' symbol. (I didn't want to use the infinity sign since hsts expires.) the arrow is a reference to the 'pre' part of preload.

I like the idea of using material design. However, if we go with Material, we should probably use an existing Material design lock icons. In addition, the circle and the the arrow are a little too small for for a tab favicon.

<img width="220" alt="screen shot 2016-04-19 at 14 03 56" src="https://cloud.githubusercontent.com/assets/248078/14655534/95f5a2de-0637-11e6-9ad3-5a5a4df11e57.png">

**Comment by lgarron** [comment]
I introduced a tentative favicon at https://github.com/chromium/hstspreload.appspot.com/commit/a55d322d2570da7fd5059eaee4f87a9227cc9c87 based on unifying common symbols for "lock" and list".

Thanks for offering a design, though – I appreciate it. :-)
