### ISSUE TITLE
Encoding variables

### ISSUE THREAD

**Issue by craigfrancis** [chromium/hstspreload#5]
This is not a security issue, as the user input is already checked with [parser.hostname](https://github.com/chromium/hstspreload/blob/master/hstspreload.appspot.com/page.html#L90), and on the server by looking for [A-Z, 0-9, Hyphen, and Dot](https://github.com/chromium/hstspreload/blob/master/hstspreload.appspot.com/hstspreload.go#L276) characters only.

But you should be encoding your variables, incase you start allowing UTF-8, and other characters.

---

With the JavaScript, use `encodeURIComponent`:

https://github.com/chromium/hstspreload/blob/master/hstspreload.appspot.com/page.html#L99

    xhr.open("POST", "/submit/" + domain, true);

https://github.com/chromium/hstspreload/blob/master/hstspreload.appspot.com/page.html#L152

    xhr.open("POST", "/clear/" + requestedDomain, true);

https://github.com/chromium/hstspreload/blob/master/hstspreload.appspot.com/page.html#L207

    <a href=\"https://www.ssllabs.com/ssltest/analyze.html?d=" + requestedDomain + "\">

---

I'm not familiar with Go, but isn't there a way of returning JSON data without creating the string yourself? maybe with `json.NewEncoder `? As that should ensure the values are properly encoded.

https://github.com/chromium/hstspreload/blob/master/hstspreload.appspot.com/hstspreload.go#L136

    fmt.Fprintf(w, `    { "name": "%s", "include_subdomains": true, "mode": "force-https" },`, key.StringID())

https://github.com/chromium/hstspreload/blob/master/hsts-review.go#L134

    fmt.Printf("    { \"name\": %q, \"include_subdomains\": true, \"mode\": \"force-https\" },\n", result.name)

---

As an aside, it would be nice if this used a standard `<form>`, where the server responded with a HTML page without the need to use JavaScript :-)

And provide a `<label>` for the input, as that will help with a11y:

http://wave.webaim.org/report#/https://hstspreload.appspot.com/

**Comment by lgarron** [comment]
Thanks for the input! I'm still getting used to this code myself, and I'm glad to have more eyes on it.

Internationalized domain names have been submitted through the preload form successfully; I don't intend to spend too much time fixing up Unicode stuff, but will happily accept a pull request. :-)

> I'm not familiar with Go, but isn't there a way of returning JSON data without creating the string yourself? 

The printed data is not actually JSON, but a bunch of JSON rows using the same formatting as [transport_security_state_static.json](https://code.google.com/p/chromium/codesearch#chromium/src/net/http/transport_security_state_static.json). We could probably fix that once #1 is landed.

> As an aside, it would be nice if this used a standard <form>, where the server responded with a HTML page without the need to use JavaScript :-)

In principle, I agree. I also want to add a consent checkbox and a submit button (#3).

However, the code is currently very minimal (no templating), and I'd like to make sure that whatever we do doesn't increase the surface area too much.

> And provide a <label> for the input, as that will help with a11y:

How about placing the the label in the `<h2>`?

**Comment by craigfrancis** [comment]
I've added pull request https://github.com/chromium/hstspreload/pull/8

I probably shouldn't touch the Go code for unicode checking, as that's certainly outside of my skill set... but it's good to know that the `range` loop it uses does [split by unicode character/rune](https://blog.golang.org/strings#TOC_6.).

And yes, a label within the `<h2>` is a good solution.

Ideally there would be a submit button, but that will require some layout changes (my design skills are even worse than my knowledge on Go).

---

As to the JSON encoding, are you sure?

It looks like [fmt.Fprintf](https://golang.org/pkg/fmt/#Fprintf) is just a way to print a formatted string, where those 2 examples ([hstspreload.go:137](https://github.com/chromium/hstspreload/blob/master/hstspreload.appspot.com/hstspreload.go#L137) and [hsts-review.go:134](https://github.com/chromium/hstspreload/blob/master/hsts-review.go#L134)) are using `"%s"` or `%q` for the `name` properties.

The first one sending data back to the browser via `http.ResponseWriter` via the [/pending](https://hstspreload.appspot.com/pending) URL, which shouldn't have any special characters at the moment, but may in the future :-)

**Comment by craigfrancis** [comment]
Pull request https://github.com/chromium/hstspreload/pull/9

**Comment by lgarron** [comment]
Some of this is moot now; also, the server part of the project is at https://github.com/chromium/hstspreload.appspot.com/ now.
