### ISSUE TITLE
Warn on obsolete TLS settings

### ISSUE THREAD

**Issue by lgarron** [chromium/hstspreload#73]

**Comment by ByJamesBurton** [comment]
I'd like to take on this issue if you don't mind?

**Comment by lgarron** [comment]
Sure, feel free to work on it.

The way I'd do this is by writing a function to inspect the `Version` and `CipherSuite` of [`ConnectionState`](https://devdocs.io/go/crypto/tls/index#ConnectionState) of the initial probe response, similar to [this `checkChain` call](https://github.com/chromium/hstspreload/blob/master/domain.go#L70).

**Comment by ByJamesBurton** [comment]
I was getting around to do this as I've been working on other projects. Sorry.
