### ISSUE TITLE
Test missing for error condition internal.domain.name.cannot_compute_etld1

### ISSUE THREAD

**Issue by marumari** [chromium/hstspreload#81]
Error code `internal.domain.name.cannot_compute_etld1` lacks any kind of test.  blogspot.com is an example domain where this error pops up on.

**Comment by lgarron** [comment]
Good idea.

**Comment by lgarron** [comment]
I was thinking of having a special message if the domain that is entered is an eTLD, because we want to encourage preloading those if at all possible.

**Comment by marumari** [comment]
Seems good to me!
