### ISSUE TITLE
Is it possible to delete all HSTS-entrys with * ?

### ISSUE THREAD

**Issue by Serkan-devel** [chromium/hstspreload#84]

**Comment by lgarron** [comment]
Could you describe in detail what you're trying to do?

Are you trying to delete entries form the preload list, or from a Chrome profile?
HSTS does not have a concept of `*`, but it does have `includeSubdomains`.

It's not possible to override preloaded HSTS entries in Chrome, if that's what you're asking about.

**Comment by Serkan-devel** [comment]
I'm trying to delete every HSTS entry. At least the not-preloaded ones.

**Comment by lgarron** [comment]
I'm not aware of a way. If you want to test something, I suggest using a new profile. If you'd like to submit a feature request to Chrome, you can do so by pressing the "New Issue" button at [crbug.com](https://bugs.chromium.org/p/chromium/issues/list).
