### ISSUE TITLE
Make timeout error summaries more descriptive

### ISSUE THREAD

**Issue by fuglede** [chromium/hstspreload#97]
This may be working as intended, but just in case it's not: After our brief Twitter discussion on sites often failing to validate after a period of time, I tried out `hstspreload batch` again, and I noticed that my home connection was not close to being able to support the 100 concurrent connections (even lowering it to 10 caused some issues). Now, in the problematic cases the error summary is

          "summary": "Cannot connect using TLS",
          "message": "We cannot connect to https://example.com using TLS (\"Get https://example.com: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)\")."

which had me a bit confused at first: even if the error summary is technically true, it seems like the error should be attributed more explicitly to the clients in these cases. Of course there will also be cases where a server failure will cause the timeout, so one would probably want to somehow ensure that that's not the case.

**Comment by lgarron** [comment]
Hmm, I haven't tried tuning concurrent connections; 100 is definitely a "works for me" value.

If it's causing problems, I'd rather tune the default concurrency or improve the retry logic than change the message.

**Comment by fuglede** [comment]
Makes sense to me. In particular, if the logic can somehow be improved to get rid of false negatives, then of course changing the message is meaningless; perhaps one we be warned and advised to turn down the concurrency count?

In any case, may as well close this one if that's not the way to go.
