### ISSUE TITLE
Tiny typo in documentation

### ISSUE THREAD

**Issue by fuglede** [chromium/hstspreload#98]
The package does not actually [have 5 parts](https://github.com/chromium/hstspreload/blob/master/doc.go#L1); only 3.

**Comment by lgarron** [comment]
Ah, nice catch. I must have forgotten to update the number when I removed parts. :-)

Would you like to submit a PR, or should I just go and fix it?

**Comment by fuglede** [comment]
I would, but that would completely go against my oppositionalilty from [earlier](https://github.com/chromium/hstspreload/pull/89#issuecomment-260179851). :)
